# Generated by Django 5.2.11 on 2026-02-23 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_email_alter_customer_phone_number'),
        ('invoices', '0002_alter_invoicelineitem_line_subtotal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('user', 'invoice_number'), name='unique_invoice_per_user'),
        ),
    ]
